name: Build Verilog Language Extension

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: false
          fetch-depth: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[17.0,18.0)'
          msbuild-architecture: x64

      - name: Show Visual Studio/MSBuild
        shell: cmd
        run: |
          where msbuild
          msbuild -version
          "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VSSDK -property installationPath

      - name: dotnet list
        shell: cmd
        run: |
          dotnet list .\VerilogLanguage.csproj package --include-transitive

      - name: Build solution
        shell: cmd
        run: |
          echo Build...
          msbuild VerilogLanguageExtension.sln ^
            /restore ^
            /t:Rebuild ^
            /p:Configuration=Release ^
            /p:Platform="Any CPU" ^
            /p:VisualStudioVersion=17.0

      - name: Upload VSIX
        if: false
        uses: actions/upload-artifact@v4
        with:
          name: VerilogLanguage.vsix
          path: |
            **\bin\Release\*.vsix
